using System;
using UnityEngine;

namespace Wave.XR
{
    [Serializable]
    public class CommitInfo
    {
        public static CommitInfo LoadFromResource()
        {
            // This commit_info will be generated by make.sh and put in <XRSDK package>/Runtime/GitIgnored/Resources
            TextAsset commitInfoAsset = (TextAsset)Resources.Load("commit_info");
            if (commitInfoAsset == null)
                return null;
            return JsonUtility.FromJson<CommitInfo>(commitInfoAsset.text);
        }

        public string commit;
        public string abbreviated_commit;
        public string refs;
    }
}